// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqpwepmdxzmuevalzkix.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxcHdlcG1keHptdWV2YWx6a2l4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNjE4MTEsImV4cCI6MjA3MDczNzgxMX0.SbZ96nDglm0cF5XR4MyHSBCyMLYGKif4j6fkrGJ-htM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});